version: '3.8'

services:
    # other services has to be added
    postgres-test:
        build:
            context: ./docker/postgres/
            dockerfile: Dockerfile
        env_file:
            - .env.test
        restart: always
        ports:
            - "5432:5432"

    backend-test:
        build:
            context: .
            dockerfile: docker/backend/Dockerfile.test
        depends_on:
            - postgres-test
        env_file:
           - .env.test
        ports:
            - "8080:8080"