version: '3.8'


services:
    postgres:
        build:
            context: ./docker/postgres/
            dockerfile: Dockerfile
        env_file:
            - .env
        restart: always
        ports:
            - "5432:5432"
        volumes:
            # Use named volume, see at the end of the file
            - pgdata:/var/lib/postgresql/data

    backend:
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
        depends_on:
            - postgres
        env_file:
            - .env
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/root/app
            # Avoid shadowing the node_modules folder
            # https://stackoverflow.com/a/32785014/3771148
            # Install is necessary for CI purposes for example
            # But for dev, install dependencies locally
            - /root/app/node_modules

    auth:
        build:
            context: .
            dockerfile: docker/authentication/Dockerfile
        env_file:
            .env
        restart: always
        volumes:
            # Avoid shadowing the node_modules folder
            # https://stackoverflow.com/a/32785014/3771148
            # Install is necessary for CI purposes for example
            # But for dev, install dependencies locally
            - ./authentication:/root/app
            - ./root/app/node_modules

    node-red-notifier:
        build:
            context: .
            dockerfile: docker/node-red-notifier/Dockerfile
        env_file:
            - .env
        restart: always
        ports:
            - "1880:1880"
        volumes:
            - ./node-red-notifier-data:/data

    # For persisting sessions related elements, like in the messenger app
    redis:
        image: redis:6.0-alpine
        command: redis-server --appendonly yes # Persists the data in docker
        env_file:
            - .env

    messenger:
        build:
            context: .
            dockerfile: docker/messenger/Dockerfile
        env_file:
            - .env
        depends_on:
            - redis
        volumes:
            # Avoid shadowing the node_modules folder
            # https://stackoverflow.com/a/32785014/3771148
            # Install is necessary for CI purposes for example
            # But for dev, install dependencies locally
            - ./messenger-app:/root/app
            - /root/app/node_modules


volumes:
    pgdata:
        # Let docker handle internally the storage of this volume
        # to prune the volume and start new with the database, use:
        #   `docker volume prune ase-blue-pgdata`
        name: ase-blue-pgdata