# Stay consistent with node red's node.js version
FROM node:12-alpine as builder

RUN mkdir /root/app
WORKDIR /root/app

COPY ./frontend/package.json /root/app
RUN yarn install

COPY ./frontend /root/app

RUN yarn build

VOLUME [ "/root/app" ]

FROM nginx:1.18.0-alpine as production-build

RUN rm -rf /usr/share/nginx/html/*

# COPY --from=builder /root/app/ /var/www
COPY --from=builder /root/app/ /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]