# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend Node.js CI

on:
  push:
    branches: [ main, develop, feature/100_improvements_sprint2 ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: ./dev/backend
      run: |
        yarn install --frozen-lockfile

    - name: Run tests
      working-directory: ./dev/backend
      uses: actions/setup-node@v1
      run: |
        yarn run test
